ls:
  .dir: kebab-case
  .ts: kebab-case
  .js: kebab-case
  .json: kebab-case
  .yaml: kebab-case
  .yml: kebab-case
  .md: kebab-case

ignore:
  - .claude
  - .github
  - .vite-hooks
  - '**/node_modules'
  - '**/dist'
  - .git
  - '**/.turbo'
  - '**/.terraform'
  - pnpm-lock.yaml
  - package.json
  - tsconfig.json
  - turbo.json
  - oxlint.json
  - .oxc.json
  - commitlint.config.js
  - lefthook.yml
  - .mise.toml
  - pnpm-workspace.yaml
  - .ls-lint.yml
  - .gitignore
  - '**/README.md'
  - CLAUDE.md
